<?php
/**
 * Child Theme Library
 *
 * WARNING: This file is a part of the core Child Theme Library.
 * DO NOT edit this file under any circumstances. Please use
 * the functions.php file to make any theme modifications.
 *
 * @package   SEOThemes\ChildThemeLibrary\Setup
 * @link      https://github.com/seothemes/child-theme-library
 * @author    SEO Themes
 * @copyright Copyright © 2018 SEO Themes
 * @license   GPL-2.0-or-later
 */

namespace SEOThemes\ChildThemeLibrary\Setup;

use function SEOThemes\ChildThemeLibrary\Utilities\get_config;

// If this file is called directly, abort.
if ( ! defined( 'ABSPATH' ) ) {

	die;

}

add_action( 'child_theme_init', __NAMESPACE__ . '\add_text_domain' );
/**
 * Add theme text domain.
 *
 * @since  1.3.0
 *
 * @return void
 */
function add_text_domain() {

	$config = get_config( 'textdomain' );

	load_child_theme_textdomain( $config['domain'], $config['path'] );

}

add_action( 'child_theme_init', __NAMESPACE__ . '\add_theme_supports' );
/**
 * Add theme supports.
 *
 * @since  1.0.0
 *
 * @return void
 */
function add_theme_supports() {

	$config = get_config( 'theme-supports' );

	foreach ( $config as $feature => $args ) {

		if ( is_array( $args ) ) {

			add_theme_support( $feature, $args );

		} else {

			add_theme_support( $args );

		}

	}

}

add_action( 'child_theme_init', __NAMESPACE__ . '\add_image_sizes' );
/**
 * Add new image sizes.
 *
 * @since  1.0.0
 *
 * @return void
 */
function add_image_sizes() {

	$config = get_config( 'image-sizes' );

	foreach ( $config as $name => $args ) {

		$crop = array_key_exists( 'crop', $args ) ? $args['crop'] : false;

		add_image_size( $name, $args['width'], $args['height'], $crop );

	}

}

add_action( 'child_theme_init', __NAMESPACE__ . '\add_post_type_supports' );
/**
 * Add post type supports.
 *
 * @since  1.0.0
 *
 * @return void
 */
function add_post_type_supports() {

	$config = get_config( 'post-type-supports' );

	foreach ( $config as $post_type => $support ) {

		add_post_type_support( $post_type, $support );

	}

}

add_action( 'child_theme_init', __NAMESPACE__ . '\add_default_headers' );
/**
 * Add default header image.
 *
 * @since  1.0.0
 *
 * @return void
 */
function add_default_headers() {

	$config = get_config( 'default-headers' );

	register_default_headers( $config );

}
