<?php
/**
 * Child Theme Library
 *
 * WARNING: This file is a part of the core Child Theme Library.
 * DO NOT edit this file under any circumstances. Please use
 * the functions.php file to make any theme modifications.
 *
 * @package   SEOThemes\ChildThemeLibrary
 * @link      https://github.com/seothemes/child-theme-library
 * @author    SEO Themes
 * @copyright Copyright © 2018 SEO Themes
 * @license   GPL-2.0-or-later
 */

namespace SEOThemes\ChildThemeLibrary;

// If this file is called directly, abort.
if ( ! defined( 'ABSPATH' ) ) {

	die;

}

spl_autoload_register( __NAMESPACE__ . '\autoload_classes' );
/**
 * Register class autoloader.
 *
 * @since  1.0.0
 *
 * @param  string $class Class to load.
 *
 * @return void
 */
function autoload_classes( $class ) {

	$search = array(
		'SEOThemes\ChildThemeLibrary\Classes\\',
		'_',
	);

	$replace = array(
		'',
		'-',
	);

	$file_name = str_replace( $search, $replace, strtolower( $class ) );

	$file = CHILD_THEME_LIB . "/classes/class-{$file_name}.php";

	if ( stream_resolve_include_path( $file ) ) {

		require_once $file;

	}
}

add_action( 'child_theme_init', __NAMESPACE__ . '\autoload', 3 );
/**
 * Autoload files.
 *
 * @since  1.1.0
 *
 * @return void
 */
function autoload() {

	$config = require_once CHILD_THEME_CONFIG;

	foreach ( $config['autoload'] as $file ) {

		$file_name = CHILD_THEME_LIB . '/' . $file . '.php';

		if ( file_exists( $file_name ) ) {

			require_once $file_name;

		}
	}
}
