<?php
/**
 * Child Theme Library
 *
 * WARNING: This file is a part of the core Child Theme Library.
 * DO NOT edit this file under any circumstances. Please use
 * the functions.php file to make any theme modifications.
 *
 * Template Name: Blog Page
 *
 * @package   SEOThemes\ChildThemeLibrary\Views
 * @link      https://github.com/seothemes/child-theme-library
 * @author    SEO Themes
 * @copyright Copyright © 2018 SEO Themes
 * @license   GPL-2.0+
 */

// If this file is called directly, abort.
if ( ! defined( 'ABSPATH' ) ) {

	die;

}

/*
 * This template is a placeholder only and is not used. It's overridden
 * with the default page_blog.php template that is included with the
 * Genesis Framework so changes made to this file will be ignored.
 */

genesis();
