<?php
/**
 * Child Theme Library
 *
 * WARNING: This file is a part of the core Child Theme Library.
 * DO NOT edit this file under any circumstances. Please use
 * the functions.php file to make any theme modifications.
 *
 * @package   SEOThemes\ChildThemeLibrary\Classes
 * @link      https://github.com/seothemes/child-theme-library
 * @author    SEO Themes
 * @copyright Copyright © 2018 SEO Themes
 * @license   GPL-2.0+
 */

/**
 * Class to handle exception.
 */
class Child_Theme_File_Exception extends Exception {

	/**
	 * Throws exceptions if config file does not exist or is not readable.
	 *
	 * @since  1.0.0
	 *
	 * @param  string $file File name.
	 *
	 * @return static
	 */
	public static function not_readable( $file ) {

		return new self( sprintf(
			// translators: Configuration file name that does not exist or is not readable.
			esc_html__( 'Something went wrong loading the configuration files. The file "%s" does either not exist or is not readable', CHILD_THEME_HANDLE ),
			$file
		) );

	}

}
