<?php
/**
 * Child Theme Library
 *
 * WARNING: This file is a part of the core Child Theme Library.
 * DO NOT edit this file under any circumstances. Please use
 * the functions.php file to make any theme modifications.
 *
 * @package   SEOThemes\ChildThemeLibrary\Structure
 * @link      https://github.com/seothemes/child-theme-library
 * @author    SEO Themes
 * @copyright Copyright © 2018 SEO Themes
 * @license   GPL-2.0+
 */

// If this file is called directly, abort.
if ( ! defined( 'ABSPATH' ) ) {

	die;

}

add_action( 'genesis_setup', 'child_theme_display_custom_logo' );
/**
 * Display custom logo in site title area.
 *
 * @since  1.0.0
 *
 * @return void
 */
function child_theme_display_custom_logo() {

	add_action( 'genesis_site_title', 'the_custom_logo', 0 );

}

