<?php
/**
 * Child Theme Library
 *
 * WARNING: This file is a part of the core Child Theme Library.
 * DO NOT edit this file under any circumstances. Please use
 * the functions.php file to make any theme modifications.
 *
 * @package   SEOThemes\ChildThemeLibrary\Structure
 * @link      https://github.com/seothemes/child-theme-library
 * @author    SEO Themes
 * @copyright Copyright © 2018 SEO Themes
 * @license   GPL-2.0-or-later
 */

namespace SEOThemes\ChildThemeLibrary\Structure;

// If this file is called directly, abort.
if ( ! defined( 'ABSPATH' ) ) {

	die;

}


add_action( 'genesis_setup', __NAMESPACE__ . '\reposition_menus' );
/**
 * Reposition navigation menus.
 *
 * @since  1.0.0
 *
 * @return void
 */
function reposition_menus() {

	remove_action( 'genesis_after_header', 'genesis_do_nav' );
	remove_action( 'genesis_after_header', 'genesis_do_subnav' );
	add_action( 'child_theme_after_title_area', 'genesis_do_nav' );
	add_action( 'child_theme_after_header_wrap', 'genesis_do_subnav' );

}
