<?php
/**
 * Child Theme Library
 *
 * WARNING: This file is a part of the core Child Theme Library.
 * DO NOT edit this file under any circumstances. Please use
 * the functions.php file to make any theme modifications.
 *
 * @package   SEOThemes\ChildThemeLibrary\Widgets
 * @link      https://github.com/seothemes/child-theme-library
 * @author    SEO Themes
 * @copyright Copyright © 2018 SEO Themes
 * @license   GPL-2.0+
 */

namespace SEOThemes\ChildThemeLibrary\Widgets;

use function SEOThemes\ChildThemeLibrary\Utilities\get_config;

// If this file is called directly, abort.
if ( ! defined( 'ABSPATH' ) ) {

	die;

}

add_action( 'widgets_init', __NAMESPACE__ . '\unregister' );
/**
 * Unregister widgets defined in the config.
 *
 * @since  1.0.0
 *
 * @return void
 */
function unregister() {

	$config = get_config( 'widgets' );

	foreach ( $config as $widget ) {

		unregister_widget( $widget );

	}

}

add_action( 'after_setup_theme', __NAMESPACE__ . '\enable_shortcodes' );
/**
 * Enables shortcodes in text widgets.
 *
 * @since  1.0.0
 *
 * @return void
 */
function enable_shortcodes() {

	add_filter( 'widget_text', 'do_shortcode' );

}
