<?php
/**
 * Child Theme Library
 *
 * WARNING: This file is a part of the core Child Theme Library.
 * DO NOT edit this file under any circumstances. Please use
 * the functions.php file to make any theme modifications.
 *
 * @package   SEOThemes\ChildThemeLibrary\Customizer
 * @link      https://github.com/seothemes/child-theme-library
 * @author    SEO Themes
 * @copyright Copyright © 2018 SEO Themes
 * @license   GPL-2.0+
 */

namespace SEOThemes\ChildThemeLibrary\Customizer;

use Kirki;
use function SEOThemes\ChildThemeLibrary\Utilities\get_config;

// If this file is called directly, abort.
if ( ! defined( 'ABSPATH' ) ) {

	die;

}

// Do not proceed if Kirki does not exist.
if ( ! class_exists( '\\Kirki' ) ) {

	return;

}

add_action( 'genesis_setup', __NAMESPACE__ . '\add_config' );
/**
 * Adds the theme's Kirki config.
 *
 * @since  1.2.0
 *
 * @link   https://aristath.github.io/kirki/docs/getting-started/config.html
 *
 * @return void
 */
function add_config() {

	Kirki::add_config(
		CHILD_THEME_HANDLE, array(
			'capability'  => 'edit_theme_options',
			'option_type' => 'theme_mod',
		)
	);

}

add_action( 'genesis_setup', __NAMESPACE__ . '\add_fields' );
/**
 * Adds settings and controls to Customizer.
 *
 * @since  1.2.0
 *
 * @return void
 */
function add_fields() {

	$fields = get_config( 'customizer' );

	foreach ( $fields as $field ) {

		Kirki::add_field( CHILD_THEME_HANDLE, $field );

	}

}

add_filter( 'kirki_config', __NAMESPACE__ . '\remove_loader' );
/**
 * Removes Kirki loader image.
 *
 * @since  1.2.0
 *
 * @param  $config the configuration array
 *
 * @return array
 */
function remove_loader( $config ) {

	return wp_parse_args( array(

		'disable_loader' => true,

	), $config );

}

add_action( 'customize_register', __NAMESPACE__ . '\remove_defaults' );
/**
 * Removes default Customizer settings.
 *
 * @since  1.2.0
 *
 * @param  object $wp_customize Global customizer object.
 *
 * @return void
 */
function remove_defaults( $wp_customize ) {

	$wp_customize->remove_control( 'background_color' );
	$wp_customize->remove_control( 'header_textcolor' );

}

add_action( 'customize_controls_print_styles', __NAMESPACE__ . '\inline_styles', 99 );
/**
 * Adds custom styles to the WordPress Customizer.
 *
 * @since  1.2.0
 *
 * @return void
 */
function inline_styles() {

	?>
	<style>
		.wp-color-result .color-alpha {
			height: 22px !important;
		}
		.wp-picker-active .iris-picker {
			margin-bottom: 12px;
		}
	</style>
	<?php

}
