<?php
/**
 * Child Theme Library
 *
 * WARNING: This file is a part of the core Child Theme Library.
 * DO NOT edit this file under any circumstances. Please use
 * the functions.php file to make any theme modifications.
 *
 * @package   SEOThemes\ChildThemeLibrary
 * @link      https://github.com/seothemes/child-theme-library
 * @author    SEO Themes
 * @copyright Copyright © 2018 SEO Themes
 * @license   GPL-2.0-or-later
 */

namespace SEOThemes\ChildThemeLibrary;

// If this file is called directly, abort.
if ( ! defined( 'ABSPATH' ) ) {

	die;

}

/**
 * Main child theme library class.
 *
 * @since   1.4.0
 */
class ChildThemeLibrary {

	/**
	 * Theme object.
	 *
	 * @since 1.4.0
	 *
	 * @var   object
	 */
	public $theme;

	/**
	 * Theme name.
	 *
	 * @since 1.4.0
	 *
	 * @var   string
	 */
	public $name;

	/**
	 * Theme url.
	 *
	 * @since 1.4.0
	 *
	 * @var   string
	 */
	public $url;

	/**
	 * Theme version.
	 *
	 * @since 1.4.0
	 *
	 * @var   string
	 */
	public $version;

	/**
	 * Theme handle.
	 *
	 * @since 1.4.0
	 *
	 * @var   string
	 */
	public $handle;

	/**
	 * Theme author.
	 *
	 * @since 1.4.0
	 *
	 * @var   string
	 */
	public $author;

	/**
	 * Theme dir.
	 *
	 * @since 1.4.0
	 *
	 * @var   string
	 */
	public $dir;

	/**
	 * Theme vendor.
	 *
	 * @since 1.4.0
	 *
	 * @var   string
	 */
	public $vendor;

	/**
	 * Theme lib.
	 *
	 * @since 1.4.0
	 *
	 * @var   string
	 */
	public $lib;

	/**
	 * Theme views.
	 *
	 * @since 1.4.0
	 *
	 * @var   string
	 */
	public $views;

	/**
	 * Theme uri.
	 *
	 * @since 1.4.0
	 *
	 * @var   string
	 */
	public $uri;

	/**
	 * Theme assets.
	 *
	 * @since 1.4.0
	 *
	 * @var   string
	 */
	public $assets;

	/**
	 * Theme config.
	 *
	 * @since 1.4.0
	 *
	 * @var   string
	 */
	public $config;

	/**
	 * Theme constructor.
	 *
	 * @since  1.4.0
	 *
	 * @param  string $config Path to theme configuration file.
	 *
	 * @return void
	 */
	public function __construct( $config ) {

		$this->config = require_once $config;

		$this->init();
		$this->modules();
		$this->autoload();

	}

	/**
	 * Initialize child theme properties.
	 *
	 * @since  1.4.0
	 *
	 * @return void
	 */
	public function init() {

		$this->theme   = wp_get_theme();
		$this->name    = $this->theme->get( 'Name' );
		$this->url     = $this->theme->get( 'ThemeURI' );
		$this->version = $this->theme->get( 'Version' );
		$this->handle  = $this->theme->get( 'TextDomain' );
		$this->author  = $this->theme->get( 'Author' );
		$this->dir     = get_stylesheet_directory();
		$this->vendor  = get_stylesheet_directory() . '/vendor';
		$this->lib     = get_stylesheet_directory() . '/vendor/seothemes/child-theme-library/src';
		$this->views   = get_stylesheet_directory() . '/vendor/seothemes/child-theme-library/resources/views';
		$this->uri     = get_stylesheet_directory_uri();
		$this->assets  = get_stylesheet_directory_uri() . '/assets';

	}

	/**
	 * Bootstrap child theme modules.
	 *
	 * @since  1.4.0
	 *
	 * @return void
	 */
	public function modules() {

		$modules = $this->config['modules'];

		foreach ( $modules as $module ) {

			$property  = strtolower( $module );
			$namespace = __NAMESPACE__ . '\\';
			$class     = $namespace . $module;

			$this->$property = new $class( $this );

		}

	}

	/**
	 * Autoloads Genesis and additional files listed in theme config.
	 *
	 * @since  1.4.0
	 *
	 * @return void
	 */
	public function autoload() {

		require_once get_template_directory() . '/lib/init.php';

		$files = $this->config['autoload'];

		foreach ( $files as $file ) {

			$file_name = $this->dir . '/' . $file . '.php';

			if ( file_exists( $file_name ) ) {

				require_once $file_name;

			}

		}

	}

}

new ChildThemeLibrary( apply_filters( 'child_theme_config', get_stylesheet_directory() . '/config/config.php' ) );
