<?php
/**
 * Child Theme Library
 *
 * WARNING: This file is a part of the core Child Theme Library.
 * DO NOT edit this file under any circumstances. Please use
 * the functions.php file to make any theme modifications.
 *
 * @package   SEOThemes\ChildThemeLibrary\Defaults
 * @link      https://github.com/seothemes/child-theme-library
 * @author    SEO Themes
 * @copyright Copyright © 2018 SEO Themes
 * @license   GPL-2.0-or-later
 */

namespace SEOThemes\ChildThemeLibrary\Defaults;

use function SEOThemes\ChildThemeLibrary\Utilities\get_config;

add_filter( 'genesis_theme_settings_defaults', __NAMESPACE__ . '\set' );
/**
 * Set default theme settings.
 *
 * @since  1.0.0
 *
 * @param  array $defaults Default theme settings.
 *
 * @return array
 */
function set( array $defaults ) {

	$config = get_config( 'genesis-settings' );

	$defaults = wp_parse_args( $config, $defaults );

	return $defaults;

}

add_action( 'after_switch_theme', __NAMESPACE__ . '\update' );
/**
 * Update theme settings upon activation.
 *
 * @since  1.0.0
 *
 * @return void
 */
function update() {

	$config = get_config();

	if ( function_exists( 'genesis_update_settings' ) ) {

		genesis_update_settings( $config['genesis-settings'] );

	}

	update_option( 'posts_per_page', $config['blog_cat_num'] );

}
