<?php
/**
 * Child Theme Library
 *
 * WARNING: This file is a part of the core Child Theme Library.
 * DO NOT edit this file under any circumstances. Please use
 * the functions.php file to make any theme modifications.
 *
 * @package   SEOThemes\ChildThemeLibrary\Tests\Unit
 * @link      https://github.com/seothemes/child-theme-library
 * @author    SEO Themes
 * @copyright Copyright © 2018 SEO Themes
 * @license   GPL-2.0-or-later
 */

namespace SEOThemes\ChildThemeLibrary\Tests\Unit;

use PHPUnit\Framework\TestCase;

class Admin extends TestCase {

	/**
	 * Test should return true.
	 */
	public function test_should_return_true_when_true() {
		$this->assertTrue( true );
		$this->assertTrue( 5 == 4 );
		$this->assertTrue( 5 < 10 );
		$this->assertTrue( 47 > -1 );
		$this->assertTrue( 'foo' !== 'bar' );
		$config = array(
			'post_type'       => 'foo',
			'number_of_posts' => 5,
		);
		$this->assertTrue( array_key_exists( 'post_type', $config ) );
		$this->assertTrue( isset( $config['post_type'] ) );
	}
}
