<?php
/**
 * Child Theme Library
 *
 * WARNING: This file is a part of the core Child Theme Library.
 * DO NOT edit this file under any circumstances. Please use
 * the functions.php file to make any theme modifications.
 *
 * @package   SEOThemes\ChildThemeLibrary
 * @link      https://github.com/seothemes/child-theme-library
 * @author    SEO Themes
 * @copyright Copyright © 2018 SEO Themes
 * @license   GPL-2.0-or-later
 */

namespace SEOThemes\ChildThemeLibrary;

/**
 * Adds layout logic to child theme.
 *
 * @since 1.4.0
 */
class Layout {

	/**
	 * Child theme object.
	 *
	 * @since 1.4.0
	 *
	 * @var   object
	 */
	public $theme;

	/**
	 * Child theme config.
	 *
	 * @since 1.4.0
	 *
	 * @var   array
	 */
	public $config;

	/**
	 * Constructor.
	 *
	 * @since  1.4.0
	 *
	 * @param  object $theme Child theme object.
	 *
	 * @return void
	 */
	public function __construct( $theme ) {

		$this->theme  = $theme;
		$this->config = $theme->config;

	}

	/**
	 * Initialize class.
	 *
	 * @since  1.5.0
	 *
	 * @return void
	 */
	public function init() {

		add_action( 'after_setup_theme', [ $this, 'register' ] );
		add_filter( 'genesis_site_layout', [ $this, 'search_page' ] );
		add_filter( 'genesis_site_layout', [ $this, 'error_404' ] );
		add_action( 'genesis_before', [ $this, 'remove_center_content_sidebars' ] );

	}

	/**
	 * Register theme layouts.
	 *
	 * @since  1.0.0
	 *
	 * @return void
	 */
	public function register() {

		$initial_layouts = array(
			'full-width-content',
			'content-sidebar',
			'sidebar-content',
			'content-sidebar-sidebar',
			'sidebar-sidebar-content',
			'sidebar-content-sidebar',
		);

		$layouts_to_remove = array_diff( $initial_layouts, $this->config['layouts'] );
		$custom_layouts    = array_diff( $this->config['layouts'], $initial_layouts );

		foreach ( $layouts_to_remove as $layout_to_remove ) {

			genesis_unregister_layout( $layout_to_remove );

		}

		foreach ( $custom_layouts as $custom_layout ) {

			genesis_register_layout(
				$custom_layout, array(
					'label' => ucwords( str_replace( '-', ' ', $custom_layout ) ),
					'img'   => $this->theme->uri . '/assets/img/' . $custom_layout . '.gif',
				)
			);

		}

	}

	/**
	 * Gets a custom page layout for the search results page.
	 *
	 * @since  1.0.0
	 *
	 * @param  string $layout Layout to return.
	 *
	 * @return string
	 */
	public function search_page( $layout ) {

		if ( is_search() ) {

			$page = get_page_by_path( 'search' );

			if ( $page ) {

				$field  = genesis_get_custom_field( '_genesis_layout', $page->ID );
				$layout = $field ? $field : genesis_get_option( 'site_layout' );

			}
		}

		return $layout;

	}

	/**
	 * Gets a custom page layout for the error 404 page.
	 *
	 * @since  1.0.0
	 *
	 * @param  string $layout Layout to return.
	 *
	 * @return string
	 */
	public function error_404( $layout ) {

		if ( is_404() ) {

			$page = get_page_by_path( 'error-404' );

			if ( $page ) {

				$field  = genesis_get_custom_field( '_genesis_layout', $page->ID );
				$layout = $field ? $field : genesis_get_option( 'site_layout' );

			}
		}

		return $layout;

	}

	/**
	 * Remove sidebars for center content layout.
	 *
	 * @since  1.0.0
	 *
	 * @return void
	 */
	public function remove_center_content_sidebars() {

		$site_layout = genesis_site_layout();

		if ( 'center-content' !== $site_layout ) {

			return;

		}

		add_filter( 'genesis_site_layout', '__genesis_return_full_width_content' );

	}

}
