<?php
/**
 * Child Theme Library
 *
 * WARNING: This file is a part of the core Child Theme Library.
 * DO NOT edit this file under any circumstances. Please use
 * the functions.php file to make any theme modifications.
 *
 * @package   SEOThemes\ChildThemeLibrary\Tests\Unit
 * @link      https://github.com/seothemes/child-theme-library
 * @author    SEO Themes
 * @copyright Copyright © 2018 SEO Themes
 * @license   GPL-2.0-or-later
 */

namespace SEOThemes\ChildThemeLibrary\Tests\Unit;

use PHPUnit\Framework\TestCase;

class Plugins extends TestCase {

	/*
	 * Test if TGMPA file exists.
	 */
	public function test_tgmpa_class_exists() {

		$this->assertFileExists( dirname( dirname( __DIR__ ) ) . '/vendor/tgmpa/tgm-plugin-activation/class-tgm-plugin-activation.php' );

	}

}
